services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092



  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Waiting for Kafka to be ready...';

      while ! kafka-topics --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
        sleep 2;
      done;

      echo 'Kafka is ready. Creating topic...';

      kafka-topics --create \
        --if-not-exists \
        --topic heartbeat-topic \
        --bootstrap-server kafka:9092 \
        --partitions 1 \
        --replication-factor 1;

      echo 'Topic created successfully.';
      
      kafka-topics --create \
        --if-not-exists \
        --topic heartbeat-dead-letter \
        --bootstrap-server kafka:9092 \
        --partitions 1 \
        --replication-factor 1;
      echo 'Dead letter topic created successfully.';
      "
  
  producer:
    build: .
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=kafka:9092
    command: ["python", "-m", "app.producer.producer"]



  postgres:
    image: postgres:15
    container_name: kafka-postgres
    environment:
      POSTGRES_USER: heartbeat_user
      POSTGRES_PASSWORD: heartbeat_pass
      POSTGRES_DB: heartbeat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heartbeat_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kafka-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  
  consumer:
    build: .
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=kafka:9092
      - POSTGRES_HOST=postgres
    command: ["python", "-m", "app.consumer.consumer"]
    ports:
      - "8000:8000"
  

  generator:
    build: .
    command: ["python", "-m", "app.generator.generator"]


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - consumer


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/monitoring
      - ./monitoring/provisioning:/etc/monitoring/provisioning
    depends_on:
      - prometheus

  
volumes:
  postgres_data:
  grafana-storage: