{
 "title": "Real-Time Customer Heartbeat Monitoring",
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages / sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(heartbeat_messages_received_total[1m])"
    }
   ]
  },
  {
   "title": "Insert / sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(heartbeat_messages_inserted_total[1m])"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "heartbeat_consumer_lag" }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "(rate(heartbeat_messages_invalid_total[1m]) / rate(heartbeat_messages_received_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "Traffic Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(heartbeat_messages_received_total[1m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(heartbeat_messages_valid_total[1m])",
     "legendFormat": "Valid"
    },
    {
     "expr": "rate(heartbeat_messages_invalid_total[1m])",
     "legendFormat": "Invalid"
    }
   ]
  },
  {
   "title": "Consumer Lag Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "heartbeat_consumer_lag", "legendFormat": "Lag" }
   ]
  }
 ]
}